# Generated by Django 4.2.2 on 2023-06-24 05:33

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=40, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=40, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='логин')),
                ('last_name', models.CharField(default='', max_length=40, verbose_name='фамилия')),
                ('first_name', models.CharField(default='', max_length=40, verbose_name='имя')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='название проекта')),
                ('description', models.TextField(default='', verbose_name='описание проекта')),
                ('count_cols', models.SmallIntegerField(default=1, verbose_name='сколько раз звонить до дозвона по умолчанию для проекта')),
                ('file', models.FilePathField(blank=True, default='', null=True)),
                ('is_over', models.BooleanField(default=False, verbose_name='дозвоны совершены')),
                ('is_started', models.BooleanField(default=False, verbose_name='начат')),
                ('date_over', models.DateTimeField(blank=True, default='')),
                ('date_start', models.DateTimeField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', related_query_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('phone', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(79000000000), django.core.validators.MaxValueValidator(79999999999)])),
                ('count_cols', models.SmallIntegerField(default=1, verbose_name='сколько раз звонить до дозвона')),
                ('is_call', models.BooleanField(default=False, verbose_name='звонил')),
                ('is_dial', models.BooleanField(default=False, verbose_name='дозвонился')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', related_query_name='call', to='baseapp.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', related_query_name='audio', to='baseapp.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
