# Generated by Django 4.2.2 on 2023-06-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_project_date_over_alter_project_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_over',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
    ]
